version: '2'

services:
  postgres_devheaven:
    container_name: postgres_devheaven
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_devheaven
